jobs:
 - job: 'farmhash_cpp'
   pool:
     vmImage: ubuntu-16.04
   steps:
    - checkout: self
      submodules: recursive
    - script: 'cd Farmhash.Benchmarks && make benchmark-farmhash'
      displayName: make
