jobs:
 - job: 'farmhash_cpp'
   pool:
     vmImage: ubuntu-16.04
   steps:
    - checkout: self
      submodules: recursive
    - script: 'cd Farmhash.Benchmarks && make benchmark-farmhash'
      displayName: make
 - job: 'net_classic'
   pool:
     vmImage: windows-2019
   steps:
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: 'Farmhash.Sharp/Farmhash.Sharp.csproj'
        restoreDirectory: '../packages'
    - task: MSBuild@1
      inputs:
        solution: 'Farmhash.Sharp/Farmhash.Sharp.csproj'
        msbuildArguments: '/p:TargetFramework=netstandard1.0'
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: 'Classic/packages.config'
        restoreDirectory: '../packages'
    - task: MSBuild@1
      inputs:
        solution: 'Classic/Classic.csproj'
    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\Classic.dll
          !**\obj\**
        searchFolder: '$(System.DefaultWorkingDirectory)'
