jobs:
 - job: 'farmhash_cpp'
   pool:
     vmImage: ubuntu-16.04
   steps:
    - checkout: self
      submodules: recursive
    - script: 'cd Farmhash.Benchmarks && make benchmark-farmhash'
      displayName: make
 - job: 'net_classic'
   pool:
     vmImage: windows-2019
   steps:
    - task: NuGetCommand@2
      inputs:
        arguments: 'Classic/packages.config'
    - task: MSBuild@1
      inputs:
        arguments: 'Classic/Classic.csproj'
