jobs:
 - job: 'farmhash_cpp'
   pool:
     vmImage: ubuntu-16.04
   steps:
    - checkout: self
      submodules: recursive
    - script: 'cd Farmhash.Benchmarks && make benchmark-farmhash'
      displayName: make
 - job: 'net_classic'
   pool:
     vmImage: windows-2019
   steps:
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: 'Classic/packages.config'
        restoreDirectory: 'packages'
    - task: MSBuild@1
      inputs:
        solution: 'Classic/Classic.csproj'
    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\*test*.dll
          !**\*TestAdapter.dll
          !**\obj\**
        searchFolder: '$(System.DefaultWorkingDirectory)'
